version: "3"

services:

  mysql5.7:
#    image: registry.nekoimi.com/base-repos/mysql-5.7:v2
    image: mysql:5.7
    container_name: mysql5.7
    ports:
      - 3306:3306
    networks:
      - mysql-network
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "./config/conf.d:/etc/mysql/conf.d"
      - "./data/mysql:/var/lib/mysql"
      - "./data/mysql-files:/var/lib/mysql-files"
    restart: always
    privileged: true

networks:
  mysql-network:
    driver: bridge
